### ISSUE TITLE
HTTP Status code in response

### ISSUE THREAD

**Issue by undjike** [MarcinOrlowski/laravel-api-response-builder#154]
When working with cross-platform frameworks, it's sometime a nightmare to detect the status code from the headers.

I think it can be useful to display the status code in the response. 

I'm aware that I have the ability to customize the response as it is stated in the package documentation. But, I think it could be the default package behavior.

This is an example from Distancematrixapi (Google also does same for other apis)

![Screenshot_20201009-073511_Chrome.jpg](https://user-images.githubusercontent.com/57102409/95551382-97ec7300-0a02-11eb-9ca7-94a55abc066b.jpg)

**Comment by MarcinOrlowski** [comment]
But what for? Unless there's something wrong with the **transport layer** (HTTP/S) used to communicate with your API, the http code should always be 200, isn't it?

**Comment by undjike** [comment]
Not only. We can have 401, 403, 404... And others, depending on what happened in the backend and for purpose of informing the front on what exactly was the problem.

**Comment by MarcinOrlowski** [comment]
That's the point. This is fundamentally broken approach one "invented" and others follow without thinking. What you need http code for? HTTP is just a transport layer. Why you want to depend on it at all? Return proper error code in your JSON.

**Comment by undjike** [comment]
Ooh. Alright... In the light of your explanations, I understand better. Thank you.

**Comment by MarcinOrlowski** [comment]
A final note, as I am not sure I explained fully my intents (and for the potential future readers). Imagine you want to expose your API via email. Client sends URLs and payload in mail body (ignore technical details "how"), and your API returns JSON response via mail as well. Will it work? Absolutely, why wouldn't it. There's literally **nothing** that would prevent this from working. You just need small bridge and that's it. Your API get all the input it needs, and your client gets the response it expects. Perfect. Do we miss HTTP codes here? Do we need them for **anything**? No. That's why I personally think the whole idea of involving HTTP codes in  API design is purely stupid. It simply makes no sense at all. Just problems. Why would one want to have more problems? :)
