### ISSUE TITLE
Laravel 5.7 support?

### ISSUE THREAD

**Issue by mikeerickson** [MarcinOrlowski/laravel-api-response-builder#166]
Hey there,

I am looking to use a legacy version along with Laravel 5.7, however, the link from the home page to legacy has a dead link

```
https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/docs/docs/legacy.md
```

Does a Laravel 5.7 version exist, or am I SOL?

**Comment by MarcinOrlowski** [comment]
Hi, this links seems incorrect (where you got it from?) as it have "docs/" twice. Correct one is: https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/docs/legacy.md

Another thing about legacy support - I do not really rely on Laravel features that much really. It's rather  PHP version that matters because of syntax used. That's it. So if you use PHP 7.2+ with legacy Laravel then I bet you can safely try to use recent version of Response Builder as it should work just fine. The only thing that you'd need to check is the provided exception handler helper as original exception handler changed across Laravel versions and so did the helper. But even if you'd be affected, then it may be pretty easy to plant current code in old handler replacement - I simply do not support it to save time. But you should be able to make it work pretty easy.

**Comment by mikeerickson** [comment]
I clicked the link from the github page (see screenshot) The link for "legacy" on this page

https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/docs/docs.md#requirements

![image](https://user-images.githubusercontent.com/183153/97040427-c1d58780-1522-11eb-8671-cf38c9aa3499.png)

**Comment by MarcinOrlowski** [comment]
Thanks. I fixed the link.
