### ISSUE TITLE
Will docs publish at a website?

### ISSUE THREAD

**Issue by winter-ice** [MarcinOrlowski/laravel-api-response-builder#193]
**Please describe the problem**
Read docs at github is not comfortable, could you deploy it?

**Describe the solution you'd like to see**
 There is many tools can quickly do this, like `vuepress` and so on.

 With best regards.

**Comment by MarcinOrlowski** [comment]
I got no plans to publish it elsewhere. In fact docs are just markdown files (*.md) so if you want it in i.e. HTML format, just use markdown-to-html converter. But I do not have any plans publishing docs elsewhere  it is now, mainly because of maintainability. In fact I do not see much problems with current form. If you point to any specific issue, maybe I'd improve the markdown files here.
