### ISSUE TITLE
Model to response

### ISSUE THREAD

**Issue by Krato** [MarcinOrlowski/laravel-api-response-builder#4]
Hi, maybe will be fine to cast not only array objects.

Now I need to do that with my model:
```php
$users = User::get()->toArray();
return ResponseBuilder::success($users);
```

Will be greate to call like:
```php
$users = User::all();
return ResponseBuilder::success($users);
```

Thanks!

**Comment by MarcinOrlowski** [comment]
Hi,

Thanls for the suggestion. I just added support for Eloquent model in `dev-master` branch (so checkout and try). Also you can now pass anything to be returned as payload, not just arrays (however not always it makes sense, as I still need to convert it to return object as per specification, but at least you can do that if needed). Let me know how ti works for you.

**Comment by MarcinOrlowski** [comment]
I just added Collection support but I am thinking about changing the way Model is handled too. For now, Model memebers goes directly into `data` node. I am thinking about putting it inside another object, i.e. `item`. so if you want to return single model, and it exposes just i.e. `name` then it would be returned as:

    {
       "data": {
               "item": {
                      "name": "John"
                }
        }
    }

this looks like better approach because you can easily add some other data to the response and do not care if you accidentally overwrite model (except for the `item` thing - I am going to make it configurable though). Comments?

**Comment by MarcinOrlowski** [comment]
the change is now live in `dev-master`. There're also new config items - so check `vendor/.../config` for details. If nothing bad show up I will push it it out as 2.1 on monday

**Comment by MarcinOrlowski** [comment]
v2.1.0 is out now.
